"""Add monotonic ``seq`` to pipeline_message for deterministic ordering (CR-NS-018).

The Designer's gate_report and the Coordinator's verify gate_report are written
in the same transaction, so ``created_at`` (``func.now()``) is identical for both
and the board orders them non-deterministically — the Coordinator's verification
could render before the report it verifies. ``seq`` (GENERATED BY DEFAULT AS
IDENTITY) gives a monotonic insertion order; existing rows backfill in physical
insertion order (which matches in-transaction order: worker first, then verify).

Revision ID: 055
Revises: 054
Create Date: 2026-06-05

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "055"
down_revision: Union[str, None] = "054"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "pipeline_message",
        sa.Column("seq", sa.BigInteger(), sa.Identity(), nullable=False),
    )
    op.create_index(
        "ix_pipeline_message_version_seq",
        "pipeline_message",
        ["version_id", "seq"],
    )


def downgrade() -> None:
    op.drop_index("ix_pipeline_message_version_seq", table_name="pipeline_message")
    op.drop_column("pipeline_message", "seq")
