#!/usr/bin/env python3
"""Nasadiť UAT prostredie z aktuálneho kódu projektu.

Per F-003 §4.1 spec — 11-step postup (discovery, snapshot existing, cleanup,
build, port alloc, write configs, start stack, wait healthy, migrate, seed,
NGINX hint, summary).

Per Sub-round 4 §3.1 O-DS-2: Python + rich library implementation.

Spustenie:
    python scripts/uat-deploy.py <slug>
    python scripts/uat-deploy.py mager --project nex-inbox
    python scripts/uat-deploy.py dev --dry-run
"""

from __future__ import annotations

import argparse
import secrets
import subprocess
import sys
from pathlib import Path
from typing import Any

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import _uat_lib  # noqa: E402

UAT_ROOT = Path("/opt/uat")
PROJECTS_ROOT = Path("/opt/projects")
NGINX_SITES_DIR = Path("/etc/nginx/sites-available")


def check_uat_root_exists() -> bool:
    """Verify /opt/uat/ exists + is writable. Returns False with hint if not."""
    if not UAT_ROOT.exists():
        _uat_lib.console.print(
            f"[red]ERROR:[/red] {UAT_ROOT} neexistuje. "
            "Spusti pre-deploy setup per docs/runbooks/UAT_FIRST_TIME_SETUP.md:"
        )
        _uat_lib.console.print("  [yellow]sudo mkdir -p /opt/uat && sudo chown $USER:$USER /opt/uat[/yellow]")
        return False
    return True


def resolve_project(*, slug: str, project: str | None) -> str:
    """Resolve project name from slug + optional --project override."""
    return project if project else slug


def generate_uat_env(
    *,
    slug: str,
    project: str,
    version: str,
    postgres_user: str = "postgres",
    postgres_db: str | None = None,
    backend_env_vars: dict[str, str] | None = None,
    postgres_password: str | None = None,
) -> str:
    """Generate UAT .env content with detected + synthetic vars (CR-022 §C-1).

    Per F-003 §11: UAT credentials oddelené od produkcie.
    Backend env vars detected from source compose (priority: secrets randomised,
    DB connection rewritten, ${VAR} expansions → __UAT_SYNTHETIC__).

    Per F-003 §11 CR-023: ``postgres_password`` (if provided) is reused for the
    top-level ``POSTGRES_PASSWORD`` line, the ``DB_PASSWORD`` overlap (if
    present in ``backend_env_vars``), and any DB-credential-bearing entry
    inside ``backend_env_vars`` (the caller is responsible for having threaded
    the same value into ``detect_backend_env_vars(synthetic_db_password=...)``).
    Defaults to a fresh ``secrets.token_hex(32)`` when ``None`` for backward
    compatibility with tests that don't care about cross-service agreement.
    """
    if postgres_password is None:
        postgres_password = secrets.token_hex(32)
    postgres_db = postgres_db or f"{project}_uat"
    backend_env_vars = backend_env_vars or {}

    lines = [
        f"# UAT environment for slug={slug} (generated by uat-deploy.py)",
        "# Per F-003 §11: UAT credentials oddelené od produkcie.",
        "",
        f"POSTGRES_USER={postgres_user}",
        f"POSTGRES_PASSWORD={postgres_password}",
        f"POSTGRES_DB={postgres_db}",
        f"UAT_SLUG={slug}",
        f"PROJECT_VERSION={version}",
        "",
    ]

    if backend_env_vars:
        lines.append("# Detected + synthetic backend env vars (CR-022 §C-1)")
        # POSTGRES_PASSWORD overlap — backend may read DB_PASSWORD instead; use same generated value
        for key, value in sorted(backend_env_vars.items()):
            if key == "DB_PASSWORD":
                lines.append(f"{key}={postgres_password}")  # share password s postgres service
            else:
                lines.append(f"{key}={value}")

    return "\n".join(lines) + "\n"


def write_nginx_config(slug: str, *, port: int) -> Path:
    """Render + write NGINX vhost config to user-writable path.

    Output: /opt/uat/<slug>/nginx-uat-vhost.conf (no sudo required).
    Direktor manuálne `sudo cp` do /etc/nginx/sites-available/ pri aktivácii
    (per F-003 §10 + Dedo Q4: žiadny sudo v Implementer scope).
    """
    content = _uat_lib.render_template(
        "uat/nginx-uat-vhost.conf",
        {"SLUG": slug, "UAT_PORT": str(port)},
    )
    config_path = UAT_ROOT / slug / "nginx-uat-vhost.conf"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(content, encoding="utf-8")
    return config_path


def _write_uat_files(
    *,
    slug: str,
    project: str,
    port: int,
    version: str,
    backend_container_port: int,
    healthcheck_test: list[str],
    backend_dockerfile: str,
    db_creds: dict[str, Any],
    backend_env_vars: dict[str, str],
    frontend_cfg: dict[str, Any] | None,
    shared_db_password: str,
) -> Path:
    """Write docker-compose.yml + .env into /opt/uat/<slug>/. Returns uat dir.

    Per CR-021 + CR-022: full per-projekt auto-detection driven template
    rendering + synthetic .env generation.
    """
    uat_dir = UAT_ROOT / slug
    uat_dir.mkdir(parents=True, exist_ok=True)
    (uat_dir / "snapshots").mkdir(exist_ok=True)
    (uat_dir / "logs").mkdir(exist_ok=True)

    backend_host_port = port + 100
    db_port = port + 200

    project_path = PROJECTS_ROOT / project
    postgres_user = db_creds.get("POSTGRES_USER") or "postgres"
    postgres_db = db_creds.get("POSTGRES_DB") or f"{project}_uat"

    # Frontend: detected config OR fallback to PROJECT_PATH/frontend + Dockerfile
    if frontend_cfg:
        ctx = frontend_cfg["context"]
        # Convert relative source-compose context to absolute UAT context
        frontend_context = str(project_path / ctx.lstrip("./")) if ctx.startswith(".") else ctx
        frontend_dockerfile = frontend_cfg["dockerfile"]
        frontend_build_args = frontend_cfg["build_args"]
        frontend_container_port = frontend_cfg.get("container_port", 80)
    else:
        frontend_context = str(project_path / "frontend")
        frontend_dockerfile = "Dockerfile"
        frontend_build_args = {}
        frontend_container_port = 80

    compose = _uat_lib.render_template(
        "uat/docker-compose.yml.j2",
        {
            "SLUG": slug,
            "UAT_PORT": str(port),
            "BACKEND_HOST_PORT": str(backend_host_port),
            "BACKEND_PORT": str(backend_container_port),
            "BACKEND_HEALTHCHECK_TEST": healthcheck_test,
            "BACKEND_DOCKERFILE": backend_dockerfile,
            "DB_PORT": str(db_port),
            "PROJECT_PATH": str(project_path),
            "PROJECT_NAME": project,
            "POSTGRES_USER": postgres_user,
            "POSTGRES_DB": postgres_db,
            "FRONTEND_CONTEXT": frontend_context,
            "FRONTEND_DOCKERFILE": frontend_dockerfile,
            "FRONTEND_BUILD_ARGS": frontend_build_args,
            "FRONTEND_CONTAINER_PORT": str(frontend_container_port),
        },
    )
    (uat_dir / "docker-compose.yml").write_text(compose, encoding="utf-8")

    env_content = generate_uat_env(
        slug=slug,
        project=project,
        version=version,
        postgres_user=postgres_user,
        postgres_db=postgres_db,
        backend_env_vars=backend_env_vars,
        postgres_password=shared_db_password,
    )
    (uat_dir / ".env").write_text(env_content, encoding="utf-8")
    (uat_dir / ".env").chmod(0o600)

    return uat_dir


def _print_summary(
    *,
    slug: str,
    port: int,
    version: str,
    dry_run: bool,
    backend_container_port: int = 8000,
) -> None:
    mode = "[yellow]DRY-RUN[/yellow]" if dry_run else "[green]DEPLOYED[/green]"
    _uat_lib.console.print(f"\n=== UAT {mode} for slug={slug} (v{version}) ===")
    _uat_lib.console.print(
        _uat_lib.status_table(
            {
                "URL": f"https://uat-{slug}.isnex.eu",
                "Frontend port (local)": f"127.0.0.1:{port}",
                "Backend port (host→container)": f"127.0.0.1:{port + 100} → {backend_container_port}",
                "Postgres port (local)": f"127.0.0.1:{port + 200}",
                "Compose": str(UAT_ROOT / slug / "docker-compose.yml"),
                "NGINX config (local)": str(UAT_ROOT / slug / "nginx-uat-vhost.conf"),
                "NGINX config (final, sudo)": str(NGINX_SITES_DIR / f"uat-{slug}.conf"),
            }
        )
    )

    if not dry_run:
        local_path = UAT_ROOT / slug / "nginx-uat-vhost.conf"
        final_path = NGINX_SITES_DIR / f"uat-{slug}.conf"
        _uat_lib.console.print("\n[yellow]Aktivácia NGINX (sudo required, mimo skript scope):[/yellow]")
        _uat_lib.console.print(f"  sudo cp {local_path} {final_path}")
        _uat_lib.console.print(f"  sudo ln -sf {final_path} /etc/nginx/sites-enabled/")
        _uat_lib.console.print("  sudo nginx -t && sudo systemctl reload nginx")


def deploy(
    slug: str,
    *,
    project: str | None = None,
    dry_run: bool = False,
    version: str = "v0.0.0-dev",
    backend_port_override: int | None = None,
    health_endpoint_override: str | None = None,
    alembic_strategy_override: str = "auto",
    skip_env_detection: bool = False,
    db_user_override: str | None = None,
    db_name_override: str | None = None,
) -> int:
    """Main deploy orchestrator per F-003 §4.1 11-step postup.

    Per CR-021 + CR-022: comprehensive per-projekt auto-detection (backend port,
    healthcheck, dockerfile, DB creds, env vars, frontend, alembic strategy)
    with CLI overrides for edge cases.
    """
    _uat_lib.validate_slug(slug)

    if not check_uat_root_exists():
        return 1

    resolved_project = resolve_project(slug=slug, project=project)
    _uat_lib.validate_slug(resolved_project)

    project_path = PROJECTS_ROOT / resolved_project
    if not project_path.exists():
        _uat_lib.console.print(f"[red]ERROR:[/red] project directory not found: {project_path}")
        return 1

    # CR-021: backend port + healthcheck + dockerfile detection
    detected = _uat_lib.detect_backend_config(project_path)
    backend_container_port = backend_port_override if backend_port_override is not None else detected["backend_port"]
    backend_dockerfile = detected["dockerfile"]
    if detected["healthcheck_test"] and not health_endpoint_override:
        healthcheck_test = detected["healthcheck_test"]
    else:
        endpoint = health_endpoint_override or "/health"
        healthcheck_test = ["CMD", "curl", "-sf", f"http://localhost:{backend_container_port}{endpoint}"]

    # CR-022 Discovery: DB creds, backend env vars, frontend, alembic strategy
    db_creds = _uat_lib.detect_db_credentials(project_path)
    if db_user_override:
        db_creds["POSTGRES_USER"] = db_user_override
    if db_name_override:
        db_creds["POSTGRES_DB"] = db_name_override

    # CR-023: precompute shared synthetic DB password before backend env detection
    # so POSTGRES_PASSWORD .env line, DB_PASSWORD overlap, and DATABASE_URL
    # embedded password all agree (postgres container init vs backend connect).
    shared_db_password = secrets.token_hex(32)
    backend_env_vars = (
        {}
        if skip_env_detection
        else _uat_lib.detect_backend_env_vars(project_path, synthetic_db_password=shared_db_password)
    )
    frontend_cfg = _uat_lib.detect_frontend_config(project_path)
    alembic_detected = _uat_lib.detect_alembic_strategy(project_path)
    alembic_strategy = alembic_strategy_override if alembic_strategy_override != "auto" else alembic_detected

    # Warn about ${VAR} placeholders (per CR-022 §C-1 spec — Direktor manual override)
    placeholder_vars = [k for k, v in backend_env_vars.items() if v == _uat_lib.USER_SECRET_PLACEHOLDER]
    if placeholder_vars:
        _uat_lib.console.print("[yellow]Detected ${VAR} env-var expansion(s) in source compose:[/yellow]")
        for var in placeholder_vars:
            _uat_lib.console.print(f"  - {var} (placeholder __UAT_SYNTHETIC__)")
        _uat_lib.console.print(
            "[yellow]Direktor: ak feature requires real values pre UAT testing,[/yellow]\n"
            f"[yellow]manuálne uprav /opt/uat/{slug}/.env pred ďalším deploy.[/yellow]"
        )

    _uat_lib.console.print(
        f"[cyan]Backend config:[/cyan] port={backend_container_port}, "
        f"dockerfile={backend_dockerfile}"
        + (" [yellow](CLI override)[/yellow]" if backend_port_override else " (detected)")
    )
    _uat_lib.console.print(
        f"[cyan]DB:[/cyan] user={db_creds['POSTGRES_USER']}, db={db_creds['POSTGRES_DB'] or f'{resolved_project}_uat'}"
    )
    _uat_lib.console.print(f"[cyan]Alembic strategy:[/cyan] {alembic_strategy}")
    if frontend_cfg:
        _uat_lib.console.print(
            f"[cyan]Frontend:[/cyan] context={frontend_cfg['context']}, dockerfile={frontend_cfg['dockerfile']}"
        )

    port = _uat_lib.allocate_port(slug)
    _uat_lib.console.print(f"[cyan]Port allocated:[/cyan] {port}")

    if dry_run:
        _print_summary(
            slug=slug,
            port=port,
            version=version,
            dry_run=True,
            backend_container_port=backend_container_port,
        )
        return 0

    # Post-allocation: any failure must release the port to prevent state leak.
    try:
        uat_dir = _write_uat_files(
            slug=slug,
            project=resolved_project,
            port=port,
            version=version,
            backend_container_port=backend_container_port,
            healthcheck_test=healthcheck_test,
            backend_dockerfile=backend_dockerfile,
            db_creds=db_creds,
            backend_env_vars=backend_env_vars,
            frontend_cfg=frontend_cfg,
            shared_db_password=shared_db_password,
        )
        write_nginx_config(slug, port=port)

        # Existing snapshot (best-effort — skip if no postgres container yet)
        container = f"uat-{slug}-postgres"
        try:
            result = _uat_lib.docker_exec(
                container,
                ["pg_dump", "-U", db_creds.get("POSTGRES_USER") or "postgres"],
                capture=True,
            )
            snapshot_path = uat_dir / "snapshots" / _uat_lib.snapshot_filename(version=version, reason="pre-redeploy")
            snapshot_path.write_bytes(
                result.stdout.encode("utf-8") if isinstance(result.stdout, str) else result.stdout
            )
            snapshot_path.chmod(0o600)
            _uat_lib.console.print(f"[cyan]Pre-deploy snapshot:[/cyan] {snapshot_path}")
        except Exception:  # noqa: BLE001
            # No existing container → first-time deploy.
            pass

        # Build + start
        _uat_lib.docker_compose(["build"], cwd=uat_dir)
        _uat_lib.docker_compose(["up", "-d"], cwd=uat_dir)

        # Wait healthy on backend (use CLI-override endpoint if given, else /health)
        endpoint = health_endpoint_override or "/health"
        healthy = _uat_lib.wait_healthy(f"http://127.0.0.1:{port + 100}{endpoint}", timeout=120)
        if not healthy:
            _uat_lib.error_console.print(
                "[red]ERROR:[/red] backend not healthy after 120s — check logs:\n"
                f"  docker compose -f {uat_dir / 'docker-compose.yml'} logs"
            )
            _uat_lib.release_port(slug)
            return 1

        # CR-022: Conditional Step 8 alembic
        backend_container = f"uat-{slug}-backend"
        if alembic_strategy == "self-bootstrap":
            _uat_lib.console.print(
                "[yellow]Alembic: self-bootstrap mode — skipping external step "
                "(backend internal lifespan handler runs migrations)[/yellow]"
            )
        elif alembic_strategy == "external":
            try:
                _uat_lib.docker_exec(backend_container, ["python", "-m", "alembic", "upgrade", "head"])
                _uat_lib.console.print("[cyan]Alembic: external migrations applied (python -m alembic)[/cyan]")
            except subprocess.CalledProcessError:
                _uat_lib.console.print("[yellow]python -m alembic failed, retry s poetry run...[/yellow]")
                _uat_lib.docker_exec(backend_container, ["poetry", "run", "alembic", "upgrade", "head"])
                _uat_lib.console.print("[cyan]Alembic: external migrations applied (poetry run)[/cyan]")
        elif alembic_strategy == "skip":
            _uat_lib.console.print("[yellow]Alembic: skipped per strategy=skip[/yellow]")
    except Exception as exc:
        _uat_lib.error_console.print(f"[red]ERROR:[/red] deploy failed: {exc}")
        _uat_lib.release_port(slug)
        _uat_lib.error_console.print(f"[yellow]Port released for slug={slug}.[/yellow]")
        return 1

    _print_summary(slug=slug, port=port, version=version, dry_run=False)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Nasadiť UAT prostredie z aktuálneho kódu projektu (F-003 §4.1).",
    )
    parser.add_argument("slug", help="UAT slug (lowercase, kebab-case, e.g. 'mager', 'dev')")
    parser.add_argument(
        "--project",
        default=None,
        help="Source project name (default: same as slug)",
    )
    parser.add_argument(
        "--version",
        default="v0.0.0-dev",
        help="Project version tag for snapshots + env (e.g. 'v0.2.0')",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print plan without invoking docker / writing files",
    )
    parser.add_argument(
        "--backend-port",
        type=int,
        default=None,
        help="Override auto-detected backend container port (per CR-021).",
    )
    parser.add_argument(
        "--health-endpoint",
        type=str,
        default=None,
        help="Override auto-detected healthcheck endpoint (e.g. '/api/v1/health').",
    )
    parser.add_argument(
        "--alembic-strategy",
        choices=["auto", "self-bootstrap", "external", "skip"],
        default="auto",
        help="Override auto-detected alembic invocation mode (CR-022).",
    )
    parser.add_argument(
        "--skip-env-detection",
        action="store_true",
        help="Skip backend env vars auto-detection (use template defaults only).",
    )
    parser.add_argument(
        "--db-user",
        type=str,
        default=None,
        help="Override auto-detected POSTGRES_USER (CR-022).",
    )
    parser.add_argument(
        "--db-name",
        type=str,
        default=None,
        help="Override auto-detected POSTGRES_DB (CR-022).",
    )
    args = parser.parse_args()

    try:
        return deploy(
            args.slug,
            project=args.project,
            dry_run=args.dry_run,
            version=args.version,
            backend_port_override=args.backend_port,
            health_endpoint_override=args.health_endpoint,
            alembic_strategy_override=args.alembic_strategy,
            skip_env_detection=args.skip_env_detection,
            db_user_override=args.db_user,
            db_name_override=args.db_name,
        )
    except ValueError as exc:
        _uat_lib.error_console.print(f"[red]ERROR:[/red] slug: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
